# Generated by Django 6.0.3 on 2026-03-23 12:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_task_shared_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='owner',
        ),
        migrations.AddField(
            model_name='membership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='workspaces', through='planner.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspace',
            name='type',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('family', 'Family')], default='personal', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(default='member', max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.workspace'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'workspace')},
        ),
    ]
