# Generated by Django 6.0.3 on 2026-03-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='members',
        ),
        migrations.AddField(
            model_name='workspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workspace_images/'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
