# Generated by Django 6.0.3 on 2026-03-24 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_remove_workspace_members_workspace_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='remind_at',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='workspace',
        ),
        migrations.AddField(
            model_name='reminder',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='workspaces', through='planner.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
