# Generated by Django 6.0.3 on 2026-03-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_remove_reminder_created_at_remove_reminder_remind_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='due_datetime',
        ),
    ]
