# Generated by Django 6.0.3 on 2026-03-25 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_quicknote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicknote',
            name='shared_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_notes', to='planner.workspace'),
        ),
    ]
