# Generated by Django 6.0.3 on 2026-03-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_quicknote_shared_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicknote',
            name='display_type',
            field=models.CharField(choices=[('plain', 'Plain'), ('list', 'Bulleted list')], default='plain', max_length=10),
        ),
    ]
