# Generated by Django 6.0.3 on 2026-03-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_eventseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicknote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quicknote_images/'),
        ),
    ]
